-- One shared, persistent three-item preview quota for all paid content.
-- Authenticated users are keyed by auth.uid(); guests use a server-issued UUID cookie.

create table if not exists paid_content_preview_accesses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  visitor_id uuid,
  project_key text not null references access_projects(project_key) on update cascade on delete restrict,
  content_key text not null,
  first_accessed_at timestamptz not null default now(),
  constraint paid_content_preview_accesses_one_actor check (num_nonnulls(user_id, visitor_id) = 1),
  constraint paid_content_preview_accesses_content_key check (
    char_length(btrim(content_key)) between 3 and 250
  )
);

create unique index if not exists paid_content_preview_accesses_user_content
  on paid_content_preview_accesses(user_id, content_key)
  where user_id is not null;

create unique index if not exists paid_content_preview_accesses_visitor_content
  on paid_content_preview_accesses(visitor_id, content_key)
  where visitor_id is not null;

create index if not exists paid_content_preview_accesses_user_count
  on paid_content_preview_accesses(user_id)
  where user_id is not null;

create index if not exists paid_content_preview_accesses_visitor_count
  on paid_content_preview_accesses(visitor_id)
  where visitor_id is not null;

alter table paid_content_preview_accesses enable row level security;

revoke all on table paid_content_preview_accesses from anon, authenticated;

create or replace function claim_paid_content_access(
  _project_key text,
  _content_key text,
  _visitor_id uuid,
  _free_limit int default 3
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_user_id uuid := auth.uid();
  actor_count int;
  user_lock_key bigint;
  visitor_lock_key bigint;
begin
  if _project_key is null or not exists (
    select 1
    from access_projects
    where project_key = _project_key
      and is_enabled
  ) then
    return false;
  end if;

  if _content_key is null or char_length(btrim(_content_key)) not between 3 and 250 then
    return false;
  end if;

  if actor_user_id is null and _visitor_id is null then
    return false;
  end if;

  if actor_user_id is not null then
    user_lock_key := hashtextextended('paid-preview:user:' || actor_user_id::text, 0);
    perform pg_advisory_xact_lock(user_lock_key);

    if _visitor_id is not null then
      visitor_lock_key := hashtextextended('paid-preview:visitor:' || _visitor_id::text, 0);
      perform pg_advisory_xact_lock(visitor_lock_key);

      insert into paid_content_preview_accesses (user_id, project_key, content_key, first_accessed_at)
      select actor_user_id, project_key, content_key, first_accessed_at
      from paid_content_preview_accesses
      where visitor_id = _visitor_id
      on conflict (user_id, content_key) where user_id is not null do nothing;

      delete from paid_content_preview_accesses
      where visitor_id = _visitor_id;
    end if;

    if public.has_active_project_access(_project_key) then
      return true;
    end if;

    if exists (
      select 1
      from paid_content_preview_accesses
      where user_id = actor_user_id
        and content_key = btrim(_content_key)
    ) then
      return true;
    end if;

    select count(*)::int
    into actor_count
    from paid_content_preview_accesses
    where user_id = actor_user_id;

    if actor_count >= greatest(coalesce(_free_limit, 0), 0) then
      return false;
    end if;

    insert into paid_content_preview_accesses (user_id, project_key, content_key)
    values (actor_user_id, _project_key, btrim(_content_key));

    return true;
  end if;

  visitor_lock_key := hashtextextended('paid-preview:visitor:' || _visitor_id::text, 0);
  perform pg_advisory_xact_lock(visitor_lock_key);

  if exists (
    select 1
    from paid_content_preview_accesses
    where visitor_id = _visitor_id
      and content_key = btrim(_content_key)
  ) then
    return true;
  end if;

  select count(*)::int
  into actor_count
  from paid_content_preview_accesses
  where visitor_id = _visitor_id;

  if actor_count >= greatest(coalesce(_free_limit, 0), 0) then
    return false;
  end if;

  insert into paid_content_preview_accesses (visitor_id, project_key, content_key)
  values (_visitor_id, _project_key, btrim(_content_key));

  return true;
end;
$$;

revoke all on function claim_paid_content_access(text, text, uuid, int) from public;
grant execute on function claim_paid_content_access(text, text, uuid, int) to anon, authenticated;
