import task1TypePractice from "@/data/writing/task1-type-practice.json";
import writingModelAnswers from "@/data/writing/model-answers.json";

export type WritingTask = "task1" | "task2";

export type WritingVocabularyItem = {
  definitionCn: string;
  level?: string;
  partOfSpeech?: string;
  phonetic?: string;
  term: string;
  ukAudioUrl?: string;
  ukPhonetic?: string;
  usAudioUrl?: string;
  usPhonetic?: string;
};

export type WritingQuestion = {
  answerImage?: string;
  book: string;
  category: string;
  id: string;
  image?: string;
  modelAnswer?: string[];
  modelAnswerVocabulary?: WritingVocabularyItem[];
  prompt: string;
  shortTitle: string;
  task: WritingTask;
  test: string;
  title: string;
  wordTarget: number;
};

export type WritingCategory = {
  description: string;
  id: string;
  label: string;
  labelEnglish: string;
  task: WritingTask;
};

export const WRITING_CATEGORIES: WritingCategory[] = [
  {
    id: "line-graph",
    label: "折线图",
    labelEnglish: "Line Graph",
    description: "识别趋势、转折与多组数据之间的变化关系。",
    task: "task1",
  },
  {
    id: "bar-chart",
    label: "柱状图",
    labelEnglish: "Bar Chart",
    description: "比较不同类别、年份或群体之间的显著差异。",
    task: "task1",
  },
  {
    id: "pie-chart",
    label: "饼图",
    labelEnglish: "Pie Chart",
    description: "概括构成比例，并找出最大、最小与主要变化。",
    task: "task1",
  },
  {
    id: "table",
    label: "表格",
    labelEnglish: "Table",
    description: "从密集数据中筛选主线，完成有效分组与比较。",
    task: "task1",
  },
  {
    id: "map",
    label: "地图题",
    labelEnglish: "Map",
    description: "描述地点、布局和不同时期的空间变化。",
    task: "task1",
  },
  {
    id: "process",
    label: "流程图",
    labelEnglish: "Process",
    description: "按阶段组织自然过程或人工生产流程。",
    task: "task1",
  },
  {
    id: "mixed",
    label: "混合图",
    labelEnglish: "Mixed Charts",
    description: "整合两种以上图表，建立跨图数据联系。",
    task: "task1",
  },
  {
    id: "opinion",
    label: "观点类",
    labelEnglish: "Opinion",
    description: "明确立场，并用完整论证回答同意、不同意或利弊权衡。",
    task: "task2",
  },
  {
    id: "discussion",
    label: "双边讨论",
    labelEnglish: "Discussion",
    description: "公平讨论双方观点，并给出自己的判断。",
    task: "task2",
  },
  {
    id: "advantages",
    label: "利弊分析",
    labelEnglish: "Advantages & Disadvantages",
    description: "比较正反影响，处理 outweigh 等权衡要求。",
    task: "task2",
  },
  {
    id: "causes-solutions",
    label: "原因与解决",
    labelEnglish: "Cause & Solution Essay",
    description: "分析问题成因，并提出与原因对应的解决措施。",
    task: "task2",
  },
  {
    id: "two-part",
    label: "两问型",
    labelEnglish: "Two-part Question",
    description: "拆解两个问题，确保每一问都有清楚、均衡的回应。",
    task: "task2",
  },
];

const task1Instruction =
  "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.";

const CORE_WRITING_QUESTIONS: WritingQuestion[] = [
  {
    id: "ci4-test1-task1",
    book: "CI4",
    test: "Test 1",
    task: "task1",
    category: "table",
    title: "The proportion of Australian families living in poverty in 1999",
    shortTitle: "澳大利亚不同家庭类型的贫困比例",
    prompt: task1Instruction,
    image: "/writing/task1/image1.png",
    wordTarget: 150,
  },
  {
    id: "ci4-test3-task1",
    book: "CI4",
    test: "Test 3",
    task: "task1",
    category: "bar-chart",
    title: "Post-school qualifications in Australia by gender",
    shortTitle: "澳大利亚男女高等教育资历对比",
    prompt: task1Instruction,
    image: "/writing/task1/image2.png",
    wordTarget: 150,
  },
  {
    id: "ci5-test1-task1",
    book: "CI5",
    test: "Test 1",
    task: "task1",
    category: "line-graph",
    title: "The ageing population in Japan, Sweden and the USA",
    shortTitle: "日本、瑞典与美国老龄人口变化",
    prompt: task1Instruction,
    image: "/writing/task1/image3.png",
    wordTarget: 150,
  },
  {
    id: "ci5-test2-task1",
    book: "CI5",
    test: "Test 2",
    task: "task1",
    category: "bar-chart",
    title: "Reasons for study and employer support by age",
    shortTitle: "不同年龄段学习动机与雇主支持",
    prompt: task1Instruction,
    image: "/writing/task1/image4.png",
    wordTarget: 150,
  },
  {
    id: "ci5-test3-task1",
    book: "CI5",
    test: "Test 3",
    task: "task1",
    category: "map",
    title: "Two possible sites for a supermarket in Garlsdon",
    shortTitle: "新超市的两个备选位置",
    prompt: task1Instruction,
    image: "/writing/task1/image5.png",
    wordTarget: 150,
  },
  {
    id: "ci6-test1-task1",
    book: "CI6",
    test: "Test 1",
    task: "task1",
    category: "mixed",
    title: "Global water use and agricultural consumption",
    shortTitle: "全球用水量与农业用水对比",
    prompt: task1Instruction,
    image: "/writing/task1/image6.png",
    wordTarget: 150,
  },
  {
    id: "ci6-test3-task1",
    book: "CI6",
    test: "Test 3",
    task: "task1",
    category: "process",
    title: "The life cycle of the silkworm and silk production",
    shortTitle: "蚕的生命周期与丝绸生产流程",
    prompt: task1Instruction,
    image: "/writing/task1/image7.png",
    wordTarget: 150,
  },
  {
    id: "ci7-test2-task1",
    book: "CI7",
    test: "Test 2",
    task: "task1",
    category: "line-graph",
    title: "Consumption of beef, lamb, chicken and fish",
    shortTitle: "四类食物消费量变化",
    prompt: task1Instruction,
    image: "/writing/task1/image8.png",
    wordTarget: 150,
  },
  {
    id: "ci7-test4-task1",
    book: "CI7",
    test: "Test 4",
    task: "task1",
    category: "pie-chart",
    title: "Electricity production in Australia and France",
    shortTitle: "澳大利亚与法国发电来源",
    prompt: task1Instruction,
    image: "/writing/task1/image9.png",
    wordTarget: 150,
  },
  {
    id: "ci8-test1-task1",
    book: "CI8",
    test: "Test 1",
    task: "task1",
    category: "mixed",
    title: "Causes of worldwide land degradation",
    shortTitle: "全球土地退化原因与地区差异",
    prompt: task1Instruction,
    image: "/writing/task1/image10.png",
    wordTarget: 150,
  },
  {
    id: "ci8-test2-task1",
    book: "CI8",
    test: "Test 2",
    task: "task1",
    category: "pie-chart",
    title: "School spending in 1981, 1991 and 2001",
    shortTitle: "英国学校三年的支出构成",
    prompt: task1Instruction,
    image: "/writing/task1/image11.png",
    wordTarget: 150,
  },
  {
    id: "ci8-test4-task1",
    book: "CI8",
    test: "Test 4",
    task: "task1",
    category: "line-graph",
    title: "Goods transported in the UK by four modes",
    shortTitle: "英国四种货运方式的运输量",
    prompt: task1Instruction,
    image: "/writing/task1/image12.png",
    wordTarget: 150,
  },
  {
    id: "ci9-test2-task1",
    book: "CI9",
    test: "Test 2",
    task: "task1",
    category: "bar-chart",
    title: "Time spent on telephone calls in the UK",
    shortTitle: "英国三类电话通话时长",
    prompt: task1Instruction,
    image: "/writing/task1/image13.png",
    wordTarget: 150,
  },
  {
    id: "ci9-test4-task1",
    book: "CI9",
    test: "Test 4",
    task: "task1",
    category: "line-graph",
    title: "US energy consumption from 1980 to 2030",
    shortTitle: "美国能源消费与未来预测",
    prompt: task1Instruction,
    image: "/writing/task1/image14.png",
    wordTarget: 150,
  },
  {
    id: "ci10-test2-task1",
    book: "CI10",
    test: "Test 2",
    task: "task1",
    category: "table",
    title: "Fairtrade coffee and banana sales in Europe",
    shortTitle: "欧洲公平贸易咖啡与香蕉销量",
    prompt: task1Instruction,
    image: "/writing/task1/image15.png",
    wordTarget: 150,
  },
  {
    id: "ci10-test4-task1",
    book: "CI10",
    test: "Test 4",
    task: "task1",
    category: "process",
    title: "The life cycle of a salmon",
    shortTitle: "三文鱼的生命周期",
    prompt: task1Instruction,
    image: "/writing/task1/image16.png",
    wordTarget: 150,
  },
  {
    id: "ci14-test4-task1",
    book: "CI14",
    test: "Test 4",
    task: "task1",
    category: "map",
    title: "Grange Park in 1920 and today",
    shortTitle: "格兰奇公园今昔布局变化",
    prompt: task1Instruction,
    image: "/writing/task1/image17.png",
    wordTarget: 150,
  },
  {
    id: "ci18-test1-task2",
    book: "CI18",
    test: "Test 1",
    task: "task2",
    category: "opinion",
    title: "The most important aim of science should be to improve people’s lives.",
    shortTitle: "科学最重要的目标是否应改善人类生活",
    prompt: "To what extent do you agree or disagree with this statement? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
    wordTarget: 250,
  },
  {
    id: "ci18-test3-task2",
    book: "CI18",
    test: "Test 3",
    task: "task2",
    category: "opinion",
    title: "Rural people are moving to cities, so the countryside population is decreasing.",
    shortTitle: "农村人口向城市迁移是积极还是消极的发展",
    prompt: "Do you think this is a positive or a negative development? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
    wordTarget: 250,
  },
  {
    id: "ci10-test3-task2",
    book: "CI10",
    test: "Test 3",
    task: "task2",
    category: "opinion",
    title: "Countries are becoming more similar because the same products are available everywhere.",
    shortTitle: "全球产品趋同是积极还是消极的发展",
    prompt: "Do you think this is a positive or negative development? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
    wordTarget: 250,
  },
  {
    id: "ci6-test2-task2",
    book: "CI6",
    test: "Test 2",
    task: "task2",
    category: "discussion",
    title: "Successful sports professionals earn far more than people in other important professions.",
    shortTitle: "体育明星的高收入是否公平",
    prompt: "Some people think this is fully justified while others think it is unfair. Discuss both these views and give your own opinion.",
    wordTarget: 250,
  },
  {
    id: "ci8-test1-task2",
    book: "CI8",
    test: "Test 1",
    task: "task2",
    category: "discussion",
    title: "Who should teach children to be good members of society?",
    shortTitle: "家庭还是学校应教会孩子成为社会良好成员",
    prompt: "Some people think that parents should teach children how to be good members of society. Others believe that school is the place to learn this. Discuss both these views and give your own opinion.",
    wordTarget: 250,
  },
  {
    id: "ci18-test2-task2",
    book: "CI18",
    test: "Test 2",
    task: "task2",
    category: "discussion",
    title: "Should university students study subjects outside their main qualification?",
    shortTitle: "大学生应广泛学习还是专注主修",
    prompt: "Some university students want to learn about other subjects in addition to their main subjects. Others believe it is more important to give all their time and attention to studying for a qualification. Discuss both these views and give your own opinion.",
    wordTarget: 250,
  },
  {
    id: "ci5-test2-task2",
    book: "CI5",
    test: "Test 2",
    task: "task2",
    category: "advantages",
    title: "A gap year between high school and university",
    shortTitle: "高中毕业后工作或旅行一年的利弊",
    prompt: "Discuss the advantages and disadvantages for young people who decide to work or travel for a year before starting university studies.",
    wordTarget: 250,
  },
  {
    id: "ci9-test1-task2",
    book: "CI9",
    test: "Test 1",
    task: "task2",
    category: "advantages",
    title: "Learning a foreign language at primary school",
    shortTitle: "小学开始学习外语是否利大于弊",
    prompt: "Some experts believe it is better for children to begin learning a foreign language at primary school rather than secondary school. Do the advantages of this outweigh the disadvantages?",
    wordTarget: 250,
  },
  {
    id: "ci18-test4-task2",
    book: "CI18",
    test: "Test 4",
    task: "task2",
    category: "advantages",
    title: "The effects of an ageing population",
    shortTitle: "人口老龄化是否利大于弊",
    prompt: "Some people say an ageing population creates problems for governments. Other people think there are benefits if society has more elderly people. To what extent do the advantages outweigh the disadvantages?",
    wordTarget: 250,
  },
  {
    id: "type-task2-repeat-offenders",
    book: "题型专项",
    test: "Cause & Solution",
    task: "task2",
    category: "causes-solutions",
    title: "Many offenders commit more crimes after serving their first punishment.",
    shortTitle: "罪犯为何再犯及如何解决",
    prompt: "Why is this happening, and what measures can be taken to tackle this problem?",
    wordTarget: 250,
  },
  {
    id: "ci4-test2-task2",
    book: "CI4",
    test: "Test 2",
    task: "task2",
    category: "two-part",
    title: "Happiness is considered very important in life.",
    shortTitle: "幸福为何难以定义，又由哪些因素决定",
    prompt: "Why is happiness difficult to define? What factors are important in achieving happiness? Give reasons for your answer and include any relevant examples.",
    wordTarget: 250,
  },
  {
    id: "ci7-test3-task2",
    book: "CI7",
    test: "Test 3",
    task: "task2",
    category: "two-part",
    title: "Job satisfaction is an important element of individual wellbeing.",
    shortTitle: "工作满意度由什么决定，人人满意是否现实",
    prompt: "What factors contribute to job satisfaction? How realistic is the expectation of job satisfaction for all workers?",
    wordTarget: 250,
  },
  {
    id: "ci4-test4-task2",
    book: "CI4",
    test: "Test 4",
    task: "task2",
    category: "two-part",
    title: "Should young children attend school as soon as possible?",
    shortTitle: "儿童尽早入学有哪些优势",
    prompt: "Some people believe children should stay at home and play until six or seven. Others believe young children should go to school as soon as possible. What are the advantages of attending school from a young age?",
    wordTarget: 250,
  },
  {
    id: "type-line-three-spreads",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "line-graph",
    title: "The consumption of three spreads from 1981 to 2007",
    shortTitle: "三种涂抹酱的消费量变化",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/line graph/The consumption of three spreads from 1981 to 2007.png",
    answerImage: "/writing/task1/by-type/line graph/The consumption of three spreads from 1981 to 2007-model answer.png",
    modelAnswer: [
      "The line graph illustrates the amount of three kinds of spreads (margarine, butter, and low fat and reduced spreads) which were consumed from 1981 to 2007. Units are measured in grams.",
      "Overall, the consumption of margarine and butter decreased over the period given, while for low fat and reduced spreads, it rose. At the start of the period, butter was the most popular spread. Margarine was the most widely consumed in the middle of the period but, by the end, low fat and reduced spreads was most popular.",
      "With regards to the amount of butter used, it began at around 140 grams and then peaked at 160 grams in 1986 before falling dramatically to about 50 grams in the last year. Likewise, approximately 90 grams of margarine was eaten in the first year, after which the figure fluctuated slightly and dropped to a low of 40 grams in 2007.",
      "On the other hand, the consumption of low fats and reduced spreads only started in 1996 at about 10 grams. This figure, which reached a high of just over 80 grams five years later, fell slightly in the final years to approximately 70 grams in 2007.",
    ],
    modelAnswerVocabulary: [
      { term: "illustrates", definitionCn: "说明；展示图表信息", phonetic: "/ˈɪləstreɪts/", partOfSpeech: "v." },
      { term: "over the period given", definitionCn: "在所给的整个时期内", partOfSpeech: "phrase" },
      { term: "widely consumed", definitionCn: "被广泛消费；消费量很大", partOfSpeech: "phrase" },
      { term: "peaked at", definitionCn: "达到……的峰值", partOfSpeech: "phrase" },
      { term: "falling dramatically", definitionCn: "大幅、急剧下降", partOfSpeech: "phrase" },
      { term: "fluctuated slightly", definitionCn: "小幅波动", partOfSpeech: "phrase" },
      { term: "dropped to a low of", definitionCn: "下降到……的低点", partOfSpeech: "phrase" },
      { term: "On the other hand", definitionCn: "另一方面，用于转向对比信息", partOfSpeech: "linking phrase" },
      { term: "reached a high of", definitionCn: "达到……的高点", partOfSpeech: "phrase" },
      { term: "approximately", definitionCn: "大约；近似地", phonetic: "/əˈprɒksɪmətli/", partOfSpeech: "adv." },
    ],
    wordTarget: 150,
  },
  {
    id: "type-line-hospital-admissions",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "line-graph",
    title: "Hospital admissions for five European hospitals",
    shortTitle: "五家医院的住院人数变化",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/line graph/The hospital admissions for five hospitals in the European country from 2004 to 2018.png",
    answerImage: "/writing/task1/by-type/line graph/The hospital admissions for five hospitals in the European country from 2004 to 2018-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-bar-household-expenditure",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "bar-chart",
    title: "Average monthly expenditure by British households",
    shortTitle: "英国家庭三年的月均支出",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/bar chart/The average monthly expenditure by British households in three years.png",
    answerImage: "/writing/task1/by-type/bar chart/The average monthly expenditure by British households in three years-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-bar-wind-energy",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "bar-chart",
    title: "Wind energy generated in four countries",
    shortTitle: "四国风力发电量变化",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/bar chart/The amount of energy generated by wind in four countries from 1985 to 2000.png",
    answerImage: "/writing/task1/by-type/bar chart/The amount of energy generated by wind in four countries from 1985 to 2000-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-pie-france-energy",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "pie-chart",
    title: "Energy production in France in two years",
    shortTitle: "法国两年的能源生产构成",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/pie chart/The comparison of different kinds of energy production of France in two years.png",
    answerImage: "/writing/task1/by-type/pie chart/The comparison of different kinds of energy production of France in two years-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-pie-electricity-generation",
    book: "题型专项",
    test: "题目",
    task: "task1",
    category: "pie-chart",
    title: "Electricity generation in two countries in 2009",
    shortTitle: "两国 2009 年的发电来源",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/pie chart/The electricity generation in two countries in 2009.png",
    wordTarget: 150,
  },
  {
    id: "type-table-indian-students",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "table",
    title: "Full-time students from India at UK universities",
    shortTitle: "英国各大学的印度全日制学生人数",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/table/the number of full-time students from India who studied at various university in the UK.png",
    answerImage: "/writing/task1/by-type/table/the number of full-time students from India who studied at various university in the UK-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-table-city-surveys",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "table",
    title: "Two surveys of city living in 1980 and 2010",
    shortTitle: "两次城市生活满意度调查",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/table/Results of two surveys done in 1980 and 2010 on various aspects of city living in a particular city.png",
    answerImage: "/writing/task1/by-type/table/Results of two surveys done in 1980 and 2010 on various aspects of city living in a particular city-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-map-meadowside",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "map",
    title: "Changes in Meadowside Village and Fountain town",
    shortTitle: "Meadowside 村与邻镇的发展变化",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/map/the changes that have taken place In Meadowside Village and Fountain, a neighboring town since 1962.png",
    answerImage: "/writing/task1/by-type/map/the changes that have taken place In Meadowside Village and Fountain, a neighboring town since 1962-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-process-cement",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "process",
    title: "Cement-making and concrete production",
    shortTitle: "水泥制造与混凝土生产流程",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/diagram or process/The stages and equipment used in the cement-making process and how cement is used to produce concrete for building purposes.png",
    answerImage: "/writing/task1/by-type/diagram or process/The stages and equipment used in the cement-making process and how cement is used to produce concrete for building purposes-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-process-frog",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "process",
    title: "The life cycle of a frog",
    shortTitle: "青蛙的生命周期",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/diagram or process/The life cycle of a frog.png",
    answerImage: "/writing/task1/by-type/diagram or process/The life cycle of a frog-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-mixed-water-distribution",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "mixed",
    title: "The world’s water distribution and use in three countries",
    shortTitle: "全球水资源分布与三国用水结构",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/multiple task/The distribution of the world's water and the use of water in three countries.png",
    answerImage: "/writing/task1/by-type/multiple task/The distribution of the world's water and the use of water in three countries-model answer.png",
    wordTarget: 150,
  },
  {
    id: "type-mixed-history-graduates",
    book: "题型专项",
    test: "附范文",
    task: "task1",
    category: "mixed",
    title: "What history graduates did after university",
    shortTitle: "历史专业毕业生去向与薪资分布",
    prompt: task1Instruction,
    image: "/writing/task1/by-type/multiple task/What history graduates did after completing their undergraduate degree course from a university in the UK.png",
    answerImage: "/writing/task1/by-type/multiple task/What history graduates did after completing their undergraduate degree course from a university in the UK-model answer.png",
    wordTarget: 150,
  },
];

const modelAnswerByQuestionId = writingModelAnswers as Record<string, string[]>;

export const WRITING_QUESTIONS: WritingQuestion[] = [
  ...CORE_WRITING_QUESTIONS,
  ...(task1TypePractice as WritingQuestion[]),
].map((question) => ({
  ...question,
  modelAnswer: question.modelAnswer ?? modelAnswerByQuestionId[question.id],
}));

export function getWritingQuestion(id: string) {
  return WRITING_QUESTIONS.find((question) => question.id === id);
}

export function getWritingQuestionsByCategory(category: string) {
  return WRITING_QUESTIONS.filter((question) => question.category === category);
}

export function getWritingCategories(task: WritingTask) {
  return WRITING_CATEGORIES.filter((category) => category.task === task);
}
